author: Box
author_url: https://twitter.com/box
github_url: https://github.com/box/box-ios-sdk
root_url: https://box.github.io/box-ios-sdk/BoxSDK/
module: BoxSDK
output: docs
theme: fullwidth
readme: ../README.md
